version: '2.0'

services:
  grafana:
    image: grafana/grafana-oss:main
    container_name: rivian-grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - TZ="America/New_York"
      - GF_SECURITY_ADMIN_USER=rivian
      - GF_SECURITY_ADMIN_PASSWORD=tankturn
    networks:
      - rivian-data
    volumes:
      - grafana:/var/lib/grafana
      - ./provisioning/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/grafana/dashboard_data:/var/lib/grafana/dashboards
  influxdb:
    image: influxdb:latest
    container_name: rivian-influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    environment:
      - TZ="America/New_York"
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=rivian
      - DOCKER_INFLUXDB_INIT_PASSWORD=tankturn
      - DOCKER_INFLUXDB_INIT_ORG=default
      - DOCKER_INFLUXDB_INIT_BUCKET=rivian_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=yyGao5gxwo6SuaVRlcYS58VuJYIe9Y7hIeYl2McAZQUHhOJmhS_CFLYqSg7lW0LQbcsicGSa5s9jsjsJaiM8ZQ==
    networks:
      - rivian-data
    volumes:
      - influxdb:/var/lib/influxdb2
  api-poller:
    container_name: rivian-api-poller
    build:
      context: build/.
      dockerfile: Dockerfile
    networks:
      - rivian-data
    environment:
      - RIVIAN_VEHICLE_ID=${RIVIAN_VEHICLE_ID}
      - RIVIAN_USERNAME=${RIVIAN_USERNAME}
      - RIVIAN_PASSWORD=${RIVIAN_PASSWORD}
networks:
  rivian-data:
    driver: bridge

volumes:
  influxdb:
  grafana: