{
 "title": "General Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "rivian",
     "query": "SELECT last(\"float\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/SOC/SOC_user') GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "energy_storage/SOC/SOC_user" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rivian",
     "query": "SELECT last(\"int\")*0.62137 FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/vehicle_energy/vehicle_range')",
     "select": [
      [
       { "params": [ "int" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/vehicle_energy/vehicle_range"
      }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "energy_storage/main/current" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/voltage_pack/V_pack_f_main_contactor"
      }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/SOC/E_SOE_pack_user_real"
      }
     ]
    }
   ]
  },
  {
   "title": "Current Software",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'telematics/ota_status/current_version_git_hash')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "telematics/ota_status/current_version_git_hash"
      }
     ]
    }
   ]
  },
  {
   "title": "Charging State",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 0 },
   "targets": [
    {
     "alias": "State",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/charger/vehicle_charger_state') GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/charger/vehicle_charger_state"
      }
     ]
    }
   ]
  },
  {
   "title": "Available Software",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'telematics/ota_status/available_version_git_hash')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "telematics/ota_status/available_version_git_hash"
      }
     ]
    }
   ]
  },
  {
   "title": "Suspension Mode",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 4 },
   "targets": [
    {
     "alias": "State",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'dynamics/modes/drive_mode_air_suspension') GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/modes/drive_mode_air_suspension"
      }
     ]
    }
   ]
  },
  {
   "title": "Motor Temp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "front_left",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/inverter_front_left/motor_temperature"
      }
     ]
    },
    {
     "alias": "front_right",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/inverter_front_right/motor_temperature"
      }
     ]
    },
    {
     "alias": "rear_left",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/inverter_rear_left/motor_temperature"
      }
     ]
    },
    {
     "alias": "rear_right",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/inverter_rear_right/motor_temperature"
      }
     ]
    }
   ]
  },
  {
   "title": "PRNDL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Lock State",
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/propulsion_status/PRNDL"
      }
     ]
    }
   ]
  },
  {
   "title": "Damping Mode",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 8 },
   "targets": [
    {
     "alias": "State",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'dynamics/modes/drive_mode_damping') GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/modes/drive_mode_damping"
      }
     ]
    }
   ]
  },
  {
   "title": "Door Locks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Lock State",
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "body/closures/global_closure_locked_state"
      }
     ]
    }
   ]
  },
  {
   "title": "Suspension Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "alias": "fl",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "int" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/suspension/ASCAHeightErrorLowPassFL_mm"
      }
     ]
    },
    {
     "alias": "fr",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "int" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/suspension/ASCAHeightErrorLowPassFR_mm"
      }
     ]
    },
    {
     "alias": "rl",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "int" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/suspension/ASCAHeightErrorLowPassRL_mm"
      }
     ]
    },
    {
     "alias": "rr",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "int" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/suspension/ASCAHeightErrorLowPassRR_mm"
      }
     ]
    }
   ]
  },
  {
   "title": "SoC",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "SoC",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "energy_storage/SOC/SOC_user" }
     ]
    }
   ]
  },
  {
   "title": "Contactor State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/mode_management/N_contactor_state')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/mode_management/N_contactor_state"
      }
     ]
    }
   ]
  },
  {
   "title": "Cabin Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rivian",
     "query": "SELECT (last(\"int\") * 9/5) +32 FROM \"rivian\" WHERE (\"sensor\" = 'thermal/hvac_cabin_control/cabin_temperature') AND $timeFilter GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "int" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "thermal/hvac_cabin_control/cabin_temperature"
      }
     ]
    }
   ]
  },
  {
   "title": "Outside Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rivian",
     "query": "SELECT (last(\"int\") * 9/5) +32 FROM \"rivian\" WHERE (\"sensor\" = 'thermal/hvac_state/outside_air_temperature') AND $timeFilter",
     "select": [
      [
       { "params": [ "int" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "thermal/hvac_cabin_control/cabin_temperature"
      }
     ]
    }
   ]
  },
  {
   "title": "Motor Torque Acheived",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "forceNm" } },
   "targets": [
    {
     "alias": "fl",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/inverter_front_left/torque_achieved"
      }
     ]
    },
    {
     "alias": "fr",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/inverter_front_left/torque_achieved"
      }
     ]
    },
    {
     "alias": "rl",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/inverter_rear_left/torque_achieved"
      }
     ]
    },
    {
     "alias": "rr",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/inverter_rear_right/torque_achieved"
      }
     ]
    }
   ]
  },
  {
   "title": "Mass Estimate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "rivian",
     "query": "SELECT last(\"int\") FROM \"rivian\" WHERE (\"sensor\" = 'dynamics/speed_performance/mass_estimate') AND $timeFilter GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "int" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/speed_performance/mass_estimate"
      }
     ]
    }
   ]
  },
  {
   "title": "Vehicle Speed (ESP)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "query": "SELECT last(\"int\")*2.20462 FROM \"rivian\" WHERE (\"sensor\" = 'dynamics/speed_performance/mass_estimate')",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/esp_status/vehicle_speed_ESP"
      }
     ]
    }
   ]
  },
  {
   "title": "Pitch/Roll",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "pitch",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "dynamics/orientation/pitch" }
     ]
    },
    {
     "alias": "roll",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "dynamics/orientation/roll" }
     ]
    },
    {
     "alias": "speed",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "dynamics/esp_status/vehicle_speed_ESP"
      }
     ]
    }
   ]
  }
 ]
}