{
 "title": "Charge Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Charge Stats",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "SoC %",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/SOC/rp_SOC_pack_absolute"
      }
     ]
    },
    {
     "alias": "volts DCFC contactor",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/voltage_pack/V_pack_f_DCFC_contactor"
      }
     ]
    },
    {
     "alias": "volts pre-contactor",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/voltage_pack/V_pack_f_pre_contactor"
      }
     ]
    },
    {
     "alias": "volts post-contactor",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/voltage_pack/V_pack_f_main_contactor"
      }
     ]
    },
    {
     "alias": "current",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/current/pack_current_high_speed"
      }
     ]
    }
   ]
  },
  {
   "title": "Contactor State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Contactor State",
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/mode_management/N_contactor_state')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/mode_management/N_contactor_state"
      }
     ]
    }
   ]
  },
  {
   "title": "Derate Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Contactor State",
     "measurement": "rivian",
     "query": "SELECT last(\"int\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/charger/EMS_charger_derate_count')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/mode_management/N_contactor_state"
      }
     ]
    }
   ]
  },
  {
   "title": "Charger AMP State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Contactor State",
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/charger/EMS_charger_AMP_state')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/mode_management/N_contactor_state"
      }
     ]
    }
   ]
  },
  {
   "title": "EVSE Remaining Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Contactor State",
     "measurement": "rivian",
     "query": "SELECT last(\"int\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/charger/EMS_charger_remainingtime_min_1')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/mode_management/N_contactor_state"
      }
     ]
    }
   ]
  },
  {
   "title": "EVSE Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Contactor State",
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/charger/EMS_charger_evse_type')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/mode_management/N_contactor_state"
      }
     ]
    }
   ]
  },
  {
   "title": "EVSE Charge Mode State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Contactor State",
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/charger/EMS_charger_mode_state')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/mode_management/N_contactor_state"
      }
     ]
    }
   ]
  },
  {
   "title": "DCFC kW",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "dcfc voltage",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "query": "SELECT last(\"float\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/voltage_pack/V_pack_f_DCFC_contactor') GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/voltage_pack/V_pack_f_DCFC_contactor"
      }
     ]
    },
    {
     "alias": "current",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "query": "SELECT last(\"int\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/charger/EMS_charger_evse_current_present') GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/voltage_pack/V_pack_f_DCFC_contactor"
      }
     ]
    }
   ]
  },
  {
   "title": "EVSE Pluglock Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Contactor State",
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/charger/EMS_charger_pluglock_request')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/mode_management/N_contactor_state"
      }
     ]
    }
   ]
  },
  {
   "title": "EVSE Pluglock Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Contactor State",
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/charger/EMS_charger_pluglock_status')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/mode_management/N_contactor_state"
      }
     ]
    }
   ]
  },
  {
   "title": "Pack Overall kW",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "dcfc voltage",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "query": "SELECT last(\"float\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/voltage_pack/V_pack_f_main_contactor') GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/voltage_pack/V_pack_f_DCFC_contactor"
      }
     ]
    },
    {
     "alias": "current",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "query": "SELECT last(\"float\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/current/pack_current_high_speed') GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/voltage_pack/V_pack_f_DCFC_contactor"
      }
     ]
    }
   ]
  },
  {
   "title": "EVSE Stats",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "target voltage",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/charger/EMS_charger_target_voltage"
      }
     ]
    },
    {
     "alias": "DCFC voltage",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/voltage_pack/V_pack_f_DCFC_contactor"
      }
     ]
    },
    {
     "alias": "target current",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/charger/EMS_charger_target_current"
      }
     ]
    },
    {
     "alias": "actual current",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "select": [
      [
       { "params": [ "int" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/current/pack_current_high_speed"
      }
     ]
    }
   ]
  },
  {
   "title": "BMS State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Contactor State",
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/state/N_BMS_state')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/mode_management/N_contactor_state"
      }
     ]
    }
   ]
  },
  {
   "title": "Cell Temp Estimated (Avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "cell estimated avg",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "query": "SELECT last(\"float\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/temperature_cell/T_cell_estimated_avg') GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/voltage_pack/V_pack_f_DCFC_contactor"
      }
     ]
    }
   ]
  },
  {
   "title": "Bus State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Contactor State",
     "measurement": "rivian",
     "query": "SELECT last(\"str\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/state/bus_state')",
     "select": [
      [
       { "params": [ "str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/mode_management/N_contactor_state"
      }
     ]
    }
   ]
  },
  {
   "title": "Cell Temp Actual (Avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "cell estimated avg",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rivian",
     "query": "SELECT last(\"float\") FROM \"rivian\" WHERE (\"sensor\" = 'energy_storage/temperature_cell/T_cell_measured_avg') GROUP BY time(1s) fill(previous)",
     "select": [
      [
       { "params": [ "float" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "sensor",
       "operator": "=",
       "value": "energy_storage/voltage_pack/V_pack_f_DCFC_contactor"
      }
     ]
    }
   ]
  }
 ]
}